/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "stm32f103x6_GPIO_Driver.h"
#include "stm32f103x6_EXTI_Driver.h"
#include "stm32f103x6_USART_Driver.h"
#include "stm32F103x6_SPI_Driver.h"

//=============macros==================

#define MCU_Act_As_Master
//#define MCU_Act_As_Slave
void clock_init()
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;
}
uint16_t data ;

void USART_IRQ_CallBack(void)
{
	MCAL_USART_ReceiveData(USART1, &data, disable);
    MCAL_USART_sendData(USART1,&data, enable);

    //Slave Selection (Low), to listen
    MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);

    // Send & Receive data
    MCAL_SPI_TX_RX(SPI1, &data, SPI_enable);

    //Force the slave select (High) idle mode
    MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
}
int main(void)
{

	clock_init();
	//=====================Init USART1===============
  USART_Config USART1_CFG;
  USART1_CFG.BaudRate        = USART_BaudRate_115200 ;
  USART1_CFG.HwFlowCtl       = USART_HwFlowCtl_NONE ;
  USART1_CFG.IRQ_Enable      =USART_IRQ_Enable_RXNEIE ;
  USART1_CFG.P_IRQ_CallBack  =USART_IRQ_CallBack;
  USART1_CFG.Payload_Length  = USART_Payload_Length_8B ;
  USART1_CFG.StopBit         = USART_StopBits_1 ;
  USART1_CFG.USART_Mode      = USART_Mode_TX_AND_RX ;
  USART1_CFG.parity          = USART_Parity_NONE ;

  MCAL_USART_Init(USART1, &USART1_CFG);
  MCAL_USART_GPIO_Set_Pins(USART1);


  //=========================Init SPI===================

  SPI_Config SPI1_CFG ;

  SPI1_CFG.Baud_Rate     = SPI_BaudRate_Prescaler_8 ;
  SPI1_CFG.CLK_Phase     = SPI_CLK_Phase_second_edge ;
  SPI1_CFG.CLK_Polarity  = SPI_CLK_Polarity_HIGH_idle ;
  SPI1_CFG.Communication_Mode = SPI_Communication_Mode_2line_Full_duplex ;
  SPI1_CFG.Data_Order =SPI_Data_Order_MSB_First ;
  SPI1_CFG.Data_Size =SPI_Data_Size_8bit ;

#ifdef MCU_Act_As_Master
  SPI1_CFG.Device_Mode = SPI_Mode_Master ;
  SPI1_CFG.IRQ_Enable = SPI_IRQ_ENABLE_NONE ;
  SPI1_CFG.NSS = SPI_NSS_SW_Set ;
  SPI1_CFG.P_IRQ_CallBack =NULL ;

  //configure ss pA4 by GPIO

  GPIO_PinConfig_t ss_cfg  ;

  ss_cfg.GPIO_PinNumber = GPIO_PIN_4 ;
  ss_cfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
  ss_cfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP ;

  //Force the slave select (High) idle mode
  MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);

  MCAL_GPIO_Init(GPIOA, &ss_cfg);
#endif

   MCAL_SPI_Init(SPI1, &SPI1_CFG);
   MCAL_SPI_GPIO_Set_Pins(SPI1);

	while(1)
	{
	}
}

