/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdint.h"
typedef volatile unsigned int vuint32_t ;

#define RCC_BASE 0x40021000
#define RCC_IOPAEN 		(1<<2)
#define RCC_APB2ENR *(volatile uint32_t *) (RCC_BASE + 0x18)

#define GPIOA_BASE 0x40010800
#define GPIOA_CRL    *(volatile uint32_t *) (GPIOA_BASE + 0x00)
#define GPIOA_CRH    *(volatile uint32_t *) (GPIOA_BASE + 0X04)
#define GPIOA_ODR    *(volatile uint32_t *) (GPIOA_BASE + 0x0c)

#define EXTI_BASE 0x40010400
#define EXTI_IMR    *(volatile uint32_t *) (EXTI_BASE + 0x00)
#define EXTI_RTSR    *(volatile uint32_t *) (EXTI_BASE + 0x08)
#define EXTI_PR    *(volatile uint32_t *) (EXTI_BASE + 0x14)


#define NVIC_ISER0   *(volatile uint32_t *)(0xE000E100)

#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1    *(volatile uint32_t *) (AFIO_BASE + 0x08)


void clock_init()
{
	// Enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPAEN;

	//AFIOEN: Alternate function IO clock enable
	RCC_APB2ENR |=(1<<0);


}

void GPIOA_init()
{
	//	pin 13 port A output
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0x00200000;

	//pin 0 portA input ;
	GPIOA_CRL |=(1<<2);
}

int main(void)
{
	clock_init();
    GPIOA_init();
	//select port A for EXTI0
	AFIO_EXTICR1 =0x0;

	//	1: Rising trigger enabled (for Event and Interrupt) for input line.
	EXTI_RTSR |=(1<<0);

	//	1: Interrupt request from Line x is not masked
	EXTI_IMR |=(1<<0);

	//Enable NVIC IRQ T (EXTIO)
	NVIC_ISER0 |=(1<<6);

	while(1);
}

void EXTI0_IRQHandler()
{

	//IRQ is happened EXTI0 >> portA pin 0 at rising edge
	// toggle led portA pin 13
	GPIOA_ODR ^=(1<<13);

	//clear EXTI0  pending request
	EXTI_PR|=(1<<0);


}
