/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "stm32f103x6_GPIO_Driver.h"
#include "stm32f103x6_EXTI_Driver.h"
#include "stm32f103x6_USART_Driver.h"
#include "stm32F103x6_SPI_Driver.h"
#include "stm32f103x6_I2C_Driver.h"
#include "EEPROM/I2C_Slave_EEPROM.h"

//=============macros==================

void clock_init()
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;
}

int main(void)
{
	clock_init();

	//Initialization of clock

	HAL_EEPROM_Init();

	/* =============== Test Case 1 =============== */
	uint8_t ch1[] = {0x01 , 0x02 , 0x03 , 0x04 , 0x05 ,0x07};
	uint8_t ch2[7] ;

	HAL_EEPROM_Write_Nbytes(0xAF, ch1, 7);
	HAL_EEPROM_Read_Nbytes(0xAF, ch2, 7);

	/* =============== Test Case 2 =============== */

	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;

	HAL_EEPROM_Write_Nbytes(0xFFF, ch1, 4);
	HAL_EEPROM_Read_Nbytes(0xFFF, ch2, 4);

	while(1)
	{
	}
}

