/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "stm32f103x6_GPIO_Driver.h"
#include "stm32f103x6_EXTI_Driver.h"
#include "stm32f103x6_USART_Driver.h"

#include "LCD/LCD.h"
#include "Keypad/Keypad.h"
void clock_init()
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;
}
uint16_t data ;

void USART_IRQ_CallBack(void)
{
	MCAL_USART_ReceiveData(USART1, &data, disable);
    MCAL_USART_sendData(USART1,&data, enable);
}
int main(void)
{

	clock_init();

  USART_Config USART1_CFG ;
  USART1_CFG.BaudRate        = USART_BaudRate_115200 ;
  USART1_CFG.HwFlowCtl       = USART_HwFlowCtl_NONE ;
  USART1_CFG.IRQ_Enable      =USART_IRQ_Enable_RXNEIE ;
  USART1_CFG.P_IRQ_CallBack  =USART_IRQ_CallBack ;
  USART1_CFG.Payload_Length  = USART_Payload_Length_8B ;
  USART1_CFG.StopBit         = USART_StopBits_1 ;
  USART1_CFG.USART_Mode      = USART_Mode_TX_AND_RX ;
  USART1_CFG.parity          = USART_Parity_NONE ;

  MCAL_USART_Init(USART1, &USART1_CFG);
  MCAL_USART_GPIO_Set_Pins(USART1);

	while(1)
	{
	}
}

